### ISSUE TITLE
cannot open audit interface - aborting

### ISSUE THREAD

**Issue by hoahuathien** [Neo-Oli/termux-ubuntu#25]
when i install mysql-server, i get error 

> cannot open audit interface - aborting
> addgroup: `/usr/sbin/groudadd -g 101 mysql` return error code 1. Exiting.
> ...

Please help!

**Comment by Neo-Oli** [comment]
Try building a chroot with the "stubs" testing branch https://github.com/Neo-Oli/termux-ubuntu/tree/stubs. It creates stubs for various programms, including groupadd

**Comment by hoahuathien** [comment]
It works, I'm  really excited. Thanks for your help.

**Comment by ronnac** [comment]
I have exactly the same error when installing dbus. I did build a chroot with the "stubs" testing branch https://github.com/Neo-Oli/termux-ubuntu/tree/stubs.- - to no avail.

**Comment by ronnac** [comment]
Apparently I did correctly install the stubs branch. Now I succeeded in installing it, and I get a different error: "group 'messagebus' does not exist"
Here is the transcript.
...

$ cd ubuntu1/
$ bash ubuntu.sh
downloading ubuntu-image
--2018-04-12 13:17:52--  https://partner-images.canonical.com/core/artful/current/ubuntu-artful-core-cloudimg-arm64-root.tar.gz
Resolving partner-images.canonical.com... 91.189.88.147
Connecting to partner-images.canonical.com|91.189.88.147|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 36380394 (35M) [application/x-gzip]
Saving to: ‘ubuntu.tar.gz’

ubuntu.tar.g   0%       0  --.-KB/s              ubuntu.tar.g   0% 280.00K  1.32MB/s              ubuntu.tar.g   2% 776.00K  1.86MB/s              ubuntu.tar.g   3%   1.23M  2.00MB/s              ubuntu.tar.g   5%   1.80M  2.21MB/s              ubuntu.tar.g   7%   2.66M  2.61MB/s              ubuntu.tar.g  10%   3.60M  2.95MB/s              ubuntu.tar.g  12%   4.32M  2.98MB/s              ubuntu.tar.g  15%   5.31M  3.22MB/s              ubuntu.tar.g  17%   6.20M  3.35MB/s              ubuntu.tar.g  20%   6.98M  3.39MB/s              ubuntu.tar.g  22%   7.87M  3.49MB/s              ubuntu.tar.g  24%   8.65M  3.52MB/s              ubuntu.tar.g  27%   9.62M  3.61MB/s              ubuntu.tar.g  30%  10.63M  3.71MB/s              ubuntu.tar.g 100%  34.69M  4.49MB/s    in 8.7s

2018-04-12 13:18:00 (3.97 MB/s) - ‘ubuntu.tar.gz’ saved [36380394/36380394]

decompressing ubuntu image
fixing nameserver, otherwise it can't connect to the internet
Writing stub: usr/sbin/groupadd
Writing stub: usr/sbin/groupdel
Writing stub: usr/bin/groups
Writing stub: usr/sbin/useradd
Writing stub: usr/sbin/usermod
Writing stub: usr/sbin/userdel
Writing stub: usr/bin/chage
Writing stub: usr/bin/mesg
writing launch script
fixing shebang of start.sh
making start.sh executable
You can now launch Ubuntu with the ./start.sh script
$ ./start.sh
root@localhost:~# apr-get install dbus
bash: apr-get: command not found
root@localhost:~# apt-get install dbus
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  libapparmor1 libdbus-1-3 libexpat1
Suggested packages:
  default-dbus-session-bus | dbus-session-bus
The following NEW packages will be installed:
  dbus libapparmor1 libdbus-1-3 libexpat1
0 upgraded, 4 newly installed, 0 to remove and 0 not upgraded.
Need to get 347 kB of archives.
After this operation, 1375 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://ports.ubuntu.com/ubuntu-ports artful-updates/main arm64 libapparmor1 arm64 2.11.0-2ubuntu17.1 [25.9 kB]
Get:2 http://ports.ubuntu.com/ubuntu-ports artful/main arm64 libdbus-1-3 arm64 1.10.22-1ubuntu1 [140 kB]
Get:3 http://ports.ubuntu.com/ubuntu-ports artful/main arm64 libexpat1 arm64 2.2.3-1 [58.9 kB]
Get:4 http://ports.ubuntu.com/ubuntu-ports artful/main arm64 dbus arm64 1.10.22-1ubuntu1 [123 kB]
Fetched 347 kB in 0s (1069 kB/s)
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = (unset),
        LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package libapparmor1:arm64.
(Reading database ... 4102 files and directories currently installed.)
Preparing to unpack .../libapparmor1_2.11.0-2ubuntu17.1_arm64.deb ...
Unpacking libapparmor1:arm64 (2.11.0-2ubuntu17.1) ...
Selecting previously unselected package libdbus-1-3:arm64.
Preparing to unpack .../libdbus-1-3_1.10.22-1ubuntu1_arm64.deb ...
Unpacking libdbus-1-3:arm64 (1.10.22-1ubuntu1) ...
Selecting previously unselected package libexpat1:arm64.
Preparing to unpack .../libexpat1_2.2.3-1_arm64.deb ...
Unpacking libexpat1:arm64 (2.2.3-1) ...
Selecting previously unselected package dbus.
Preparing to unpack .../dbus_1.10.22-1ubuntu1_arm64.deb ...
Unpacking dbus (1.10.22-1ubuntu1) ...
Setting up libexpat1:arm64 (2.2.3-1) ...
Processing triggers for libc-bin (2.26-0ubuntu2.1) ...
Setting up libapparmor1:arm64 (2.11.0-2ubuntu17.1) ...
Setting up libdbus-1-3:arm64 (1.10.22-1ubuntu1) ...
Setting up dbus (1.10.22-1ubuntu1) ...
dpkg-statoverride: error: group 'messagebus' does not exist
dpkg: error processing package dbus (--configure):
 subprocess installed post-installation script returned error exit status 2
Processing triggers for libc-bin (2.26-0ubuntu2.1) ...
Errors were encountered while processing:
 dbus
E: Sub-process /usr/bin/dpkg returned an error code (1)
root@localhost:~#

**Comment by fontypete** [comment]
Did you get a fix for this @ronnac ? I have exactly the same problem.
